import './globals.css';

import { createServerClient } from '@/utils/supabaseServer';
import Footer from './components/generic/footer';
import Header from './components/generic/header';
import SupabaseListener from './supabaseListener';
import SupabaseProvider from './supabaseProvider';
// import { createServerClient } from '../utils/supabase-server';

// do not cache this layout
export const revalidate = 0;

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerClient();

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <SupabaseProvider session={session}>
          <SupabaseListener serverAccessToken={session?.access_token} />
          <Header />
          <div className="flex-grow min-h-0">
            <main className="flex flex-col justify-center items-center p-8">
              {children}
            </main>
          </div>
          <Footer />
        </SupabaseProvider>
      </body>
    </html>
  );
}
